includes:
  - configs/tsc/base.yml


model:
  name: colight
  train_model: True
  graphic: True
  vehicle_max: 1
  epsilon: 0.8
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  NEIGHBOR_NUM: 4
  NEIGHBOR_EDGE_NUM: 4
  N_LAYERS: 1
  INPUT_DIM: [64, 64]    #QCY: change from 128,128 to 64,64
  OUTPUT_DIM: [64, 64]    #QCY: change from 128,128 to 64,64
  NODE_EMB_DIM: [64, 64]    #QCY: change from 128,128 to 64,64
  NUM_HEADS: [5, 5]
  NODE_LAYER_DIMS_EACH_HEAD: [16, 16]
  OUTPUT_LAYERS: [32,32]     #QCY: change from [] to [32,32]

  one_hot: True
  phase: False


trainer:
  learning_start: 1000
  buffer_size: 5000